FROM python:3.11-slim

LABEL maintainer="yonathan-toledano"
LABEL project="QuakeWatch DevOps Final Project - Phase 1"

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]
