apiVersion: apps/v1
kind: Deployment
metadata:
  name: quakewatch-deployment
  namespace: quakewatch
  labels:
    app: quakewatch
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quakewatch
  template:
    metadata:
      labels:
        app: quakewatch
    spec:
      containers:
        - name: quakewatch
          image: yonathantoledano/quakewatch:phase1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: quakewatch-config
            - secretRef:
                name: quakewatch-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
