apiVersion: batch/v1
kind: CronJob
metadata:
  name: quakewatch-health-check
  namespace: quakewatch
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: health-check
              image: curlimages/curl:8.8.0
              command:
                - sh
                - -c
                - |
                  echo "Checking QuakeWatch service from inside the Kubernetes cluster..."
                  curl -f http://quakewatch-service:5000/
                  echo "QuakeWatch service is up and running."
