replicaCount: 1

image:
  repository: yonathantoledano/monitor
  tag: 4b6ab0c6b61a840ff7db2db82060d7c1dfc4a57f
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: traefik
  annotations: {}
  hosts: []

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

persistence:
  enabled: true
  storageClassName: local-path
  size: 1Mi

tokenSecretInitImage: busybox:1.36.1

delivery:
  sourceRepository: yonathan-toledano/Final_Project
  sourceRevision: main
  cloudProvider: AWS EC2
  infrastructureAsCode: Terraform
  orchestrator: K3S Kubernetes
  packageManager: Helm
  gitOpsController: ArgoCD
  ciProvider: GitHub Actions
  containerRegistry: Docker Hub

env:
  appEnv: production
  tokenTtlSeconds: "86400"
  publicBaseUrl: "https://finalproject.networkyonathan.com"
  appVersion: "4b6ab0c6b61a840ff7db2db82060d7c1dfc4a57f"
  deployedAt: "2026-08-15T09:55:04Z"

probes:
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
