replicaCount: 1

image:
  repository: yonathantoledano/monitor
  tag: 0f2678b39c9e45e5c7476427a33a34bb68a54404
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: traefik
  annotations: {}
  hosts: []

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

env:
  appEnv: production
  tokenTtlSeconds: "86400"
  publicBaseUrl: "https://finalproject.networkyonathan.com"
  appVersion: "0f2678b39c9e45e5c7476427a33a34bb68a54404"
  deployedAt: "2026-08-15T08:57:40Z"

probes:
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
