apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quakewatch.fullname" . }}-secret
  labels:
    {{- include "quakewatch.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secret.secretKey | quote }}
